<!-- Footer -->

<footer class="footer">
    <div class="about-col">
        <p>Subsrcibe for our upcoming latest articles and news resources</p>
        <label for="footer-email">Write your email below to get notify!</label>
        <input type="email" id="footer-email" placeholder=" Email address">
    </div>
    <div class="links-col">
        <h2>Company</h2>
        <ul>
            <li>About us</li>
            <li>Privacy Policy</li>
            <li>Terms Of Use</li>
        </ul>
    </div>
    <div class="contact-col">
        <h2>Contacts</h2>
        <ul>
            <li>
                <span class="fa-solid fa-phone"></span>
                <span>+84 0123456789</span>
            </li>
            <li>
                <span class="fa-solid fa-envelope"></span>
                <span>admin@longchau.com</span>
            </li>
            <li>
                <span class="fa-solid fa-location-pin"></span>
                <span>80 Duy Tan</span>
            </li>
        </ul>
    </div>
    <div class="icon-col">
        <span class="fa-brands fa-facebook"></span>
        <span class="fa-brands fa-instagram"></span>
        <span class="fa-brands fa-x-twitter"></span>
        <span class="fa-brands fa-pinterest"></span>
    </div>
</footer>